repos:
  # 1. Prettier: Formats HTML, CSS, JS, and more
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: ["--check"]

  # 2. ESLint: Lints JavaScript and ensures code quality
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.41.0
    hooks:
      - id: eslint
        files: \.js$

  # 3. Stylelint: Lints CSS and SCSS for style and syntax issues
  - repo: https://github.com/pre-commit/mirrors-stylelint
    rev: 15.10.0
    hooks:
      - id: stylelint
        files: \.(css|scss)$

  # 4. Check YAML: Ensures all YAML files (like workflows) are valid
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml

  # 5. Check for Trailing Whitespace: Removes trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace

  # 6. End of File Fixer: Ensures files end with a single newline
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer

  # 7. Detect Secrets: Ensures no sensitive information is committed
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
